### PR TITLE
🐛 wait_for_model fix and reanable imageSegmentation test

### LINKED ISSUE #4: `wait_for_model` not being respected / disabled imageSegmentation test
Currently the `wait_for_model` option is not being respected when using the inference package. Due to this the imageSegmentation test is failing  and is currently disabled.

### PR DESCRIPTION
**Pull request by TimMikeladze**
Closes #4 

I noticed that in the code-sample provided in #7 the "wait for model" functionality is activated via the header `X-Wait-For-Model` instead of being sent in the body of the `POST` request. There is a discrepancy with the documentation in this regard https://huggingface.co/docs/api-inference/detailed_parameters

This made me wonder: should other options such as `use_cache` also be sent as headers?

### CODE REVIEW

**Comment by coyotte508** [comment]
cc @Narsil , is it ok to pass the `wait_for_model` in the payload, or do we need to pass it as `X-Wait-For-Model` ?

**Comment by Narsil** [comment]
Both are fine.

The header is the only viable option for `image` or `audio` payloads (which are pure bytes, hence, there's no other way to pass parameters around).

This isn't documented as it was meant for internal use. If there are issues, we could just document it instead.

File: packages/inference/src/HfInference.ts [hunk 1]
```diff
@@ -653,10 +653,19 @@ export class HfInference {
 	): Promise<any> {
 		const mergedOptions = { ...this.defaultOptions, ...options };
 		const { model, ...otherArgs } = args;
+
+    const headers = {
+      Authorization: `Bearer ${this.apiKey}`,
+    }
+
+    if (mergedOptions.wait_for_model) {
```
Comment (coyotte508) [inline packages/inference/src/HfInference.ts:661]:
```suggestion
    if (options?.binary && mergedOptions.wait_for_model) {
```

From Narsil's comment

**Review by coyotte508 — COMMENTED** [review]
By the way - you should configure your editor to use tabs instead of spaces (or install the recommended extension)

Or we should add back husky ^^
