### PR TITLE
fix: better handling of symlink (Windows,...)

### LINKED ISSUE #1268: Hub snapshot_download not compatible with Windows
It is using symlink which is rejected on most Windows configurations (requires administrator priviledges)

Should use helper function similar to 

https://github.com/huggingface/huggingface_hub/blob/fcfd14361bd03f23f82efced1aa65a7cbfa4b922/src/huggingface_hub/file_download.py#L517

### PR DESCRIPTION
**Pull request by jeffmaury**
Add finer handling of symlink as it is not supported on Windows.

Fixes #1268

### CODE REVIEW

**Comment by coyotte508** [comment]
Thanks for the contribution!

cc @Wauplin @hanouticelina  for viz since it's also in the python implem

File: packages/hub/src/utils/symlink.ts [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+		_are_symlinks_supported_in_dir.set(cache_dir, true);
+
+		await fs.mkdir(cache_dir, { recursive: true });
+		const tmp_dir = await fs.mkdtemp(cache_dir);
+		try {
+			const src_path = path.join(tmp_dir, "dummy_src");
+			await fs.open(src_path, "w").then((fd) => fd.close());
+			const dst_path = path.join(tmp_dir, "dummy_dst");
+
+			const relative_src = path.relative(src_path, path.dirname(dst_path));
```
Comment (coyotte508) [inline packages/hub/src/utils/symlink.ts:64]:
```suggestion
			const relative_src = path.relative(path.dirname(dst_path), src_path);
```

I think python & JS arguments are not in the same order

File: packages/hub/src/utils/symlink.ts [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+			if (_are_symlinks_supported_in_dir.size > MAX_CACHE_SIZE) {
+				const key = _are_symlinks_supported_in_dir.keys().next().value;
+				if (key) {
+					_are_symlinks_supported_in_dir.delete(key);
+				}
+			}
+		}
+	}
+	return _are_symlinks_supported_in_dir.get(cache_dir) ?? false;
+}
```
Comment (coyotte508) [inline packages/hub/src/utils/symlink.ts:105]: Is it possible to remove this whole function?

By doing in `createSymlink` something like:

```ts
	try {
    await symlink(dest, src);
    return;
  } catch {}

  // symlink failed, copy or rename the file
```

**Review by coyotte508 — APPROVED** [review]
Thanks

I think we may still want to use relative paths (from what is said in the doc comment) on windows in the symlink, but current version is already an improvement to make it work better in windows.

Approving and  will merge in a few days

**Review by axel7083 — APPROVED** [review]
